{
  "source": "/Users/viniciusibiapina/Desktop/extraction/XMALC-LAUDO MÉDICO 16.12.25.pdf",
  "page_count": 1,
  "pages": [
    {
      "page_number": 1,
      "text": "Laudo médico\n\nPaciente: Miguel Ângelo Lima Clemente\n\nPaciente, para os devidos fins, apresenta quadro compatível com transtorno do espectro\nautista infantil, com início na primeira infância. Teve parto a termo, marcha aos 12 meses e\naquisição de fala após os 2 anos de idade. Houve desmame precoce aos 3 meses por enjoos\nfrequentes, além de relato de choro excessivo e gritos intensos no período neonatal.\n\nNo desenvolvimento comportamental e funcional, observa-se dificuldade importante de foco e\nmanutenção em atividades estruturadas, com prejuízo para desempenho em contextos\nocupacionais futuros. Apresenta brincadeiras disfuncionais, com uso repetitivo de tampinhas,\ncompreensão limitada de negativas e reação catastrófica frente a contrariedades. Há presença\nde maneirismos motores, como realização de piruetas, bem como hipersensibilidade ao toque\nfísico, especialmente no couro cabeludo, não permitindo lavar ou pentear os cabelos, o que\nimpacta diretamente as atividades de autocuidado e a rotina diária.\n\nO conjunto de achados descritos repercute de forma significativa na adaptação social, na\ntolerância a frustrações, na autonomia funcional e na previsibilidade comportamental. Em\nrelação às limitações e dificuldades futuras, há alta probabilidade de manutenção das\ndificuldades atualmente observadas, sem prognóstico de melhora funcional significativa no\ncurto e médio prazo, estimando-se persistência do quadro pelos próximos 2 anos, com\ndependência parcial de terceiros para organização da rotina e manejo comportamental.\n\nDo ponto de vista terapêutico, indica-se acompanhamento multiprofissional contínuo, com\nintervenções baseadas em terapia comportamental, terapia ocupacional com foco em integração\nsensorial e atividades de vida diária, fonoaudiologia voltada para linguagem funcional e\npragmática, além de suporte psicopedagógico para manejo de atenção, organização e adaptação\nàs demandas acadêmicas e futuras demandas laborais.\n\nCID-10: F84.0, F90.0\nAtenciosamente\n\nEmanuel Cavalcante Silva RQOE 9829\nPsiquiatra\n\nData: 16/12/2025\n\nAssinado e validado digitalmente por Emanuel Cavalcante Silva - CRM: 18396/CE para Miguel Ângelo Lima\nClemente - CPF: 110.941.543-50.\n\nAcesse o sistema emissor: https://app.tribemd.com/consulta-documentos/5B808FEB\n\nou escaneie o QR Code para verificar a validade e autenticidade do documento.\n\nPara verificar a autenticidade da assinatura no site (validar.iti.gov.br) e utilize o arquivo PDF\n\nIdentificação do emitente\n\nNome: Emanuel Cavalcante Silva\n\nCRM: 18396/CE RQE: 9829\n\nEndereço: Rua Monsenhor Bruno, 496, Apt 501, Meireles, 60115-190\nCidade: Fortaleza - CE\n\nTelefone: (85) 98206-0349\n\n- app.tribemd.com\n\nDocumento emitido pelo sistema TribeMD Assist v1.029\n",
      "words": []
        }
      ]
    }